name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify API Key is Set
        run: |
          if [ -z "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY is not set!"
            exit 1
          else
            echo "API_KEY is successfully accessed!"
          fi
